// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI_om_PqTLJnBiQVzD0xyWa99c4P6hWsc',
    appId: '1:187839264674:web:9c00b215fec865b32664fb',
    messagingSenderId: '187839264674',
    projectId: 'stage-management-app-db',
    authDomain: 'stage-management-app-db.firebaseapp.com',
    storageBucket: 'stage-management-app-db.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_5sI7Yt9md7Yq6j1Feu5AiWCrelwi5gg',
    appId: '1:187839264674:android:dc66a9fdf26075c52664fb',
    messagingSenderId: '187839264674',
    projectId: 'stage-management-app-db',
    storageBucket: 'stage-management-app-db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1lxG9w6FEyD4YcqpmOeF1QfI8lsFaHp8',
    appId: '1:187839264674:ios:03731470d5c4afe82664fb',
    messagingSenderId: '187839264674',
    projectId: 'stage-management-app-db',
    storageBucket: 'stage-management-app-db.appspot.com',
    iosBundleId: 'com.example.stageMgtApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1lxG9w6FEyD4YcqpmOeF1QfI8lsFaHp8',
    appId: '1:187839264674:ios:03731470d5c4afe82664fb',
    messagingSenderId: '187839264674',
    projectId: 'stage-management-app-db',
    storageBucket: 'stage-management-app-db.appspot.com',
    iosBundleId: 'com.example.stageMgtApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAI_om_PqTLJnBiQVzD0xyWa99c4P6hWsc',
    appId: '1:187839264674:web:2bdea9fec25844142664fb',
    messagingSenderId: '187839264674',
    projectId: 'stage-management-app-db',
    authDomain: 'stage-management-app-db.firebaseapp.com',
    storageBucket: 'stage-management-app-db.appspot.com',
  );

}